Pridaný field do Semestra a Serii na freezovanie poradia a taktiez me…
ZdruzenieSTROM/webstrom-backend pull request #53
Opened 2020-10-12 21:19 UTC by kovacspe

Príprava modelov na freezovanie poradia. Doplnený field, freezovacia metóda a get freezovaných výsledkov ak existuju

2020-10-15 18:44 UTC, mmihalik requested changes
Zatiaľ som sa na to skoro vôbec nepozrel, takže mám len gramatický fašizmus ale myslím si že správne po anglicky je frozen.

2020-10-15 22:41 UTC, kovacspe commented
Upravil som názvoslovie

2020-10-21 16:10 UTC, tomaskocak approved these changes
hmm... Dava to zmysel ze ak poradie zmrazis, teda te ho ulozis do textfieldu forzen_results, stale mozes upravovat poradie ale nikde sa to uz neprejavi a jediny sposob ako ho naozaj upravit je zmazat obsah frozen_results

Ak niekedy v buducnosti bude niekto chciet nieco upravit v zmrazenom poradi (nech uz je dovod akykolvek) viem si predstavit ze sa moze stat ze to nebude vediet urobit.

Hmm, asi je to takto vporiadku :-D

2020-10-25 21:16 UTC, Matushl reviewed
Osobne mi to pride cele fajn, funkcne, ale myslim si ze by tam predsa len mala byt moznost preulozit uz freeznute poradie...

> Ak niekedy v buducnosti bude niekto chciet nieco upravit v zmrazenom poradi (nech uz je dovod akykolvek) viem si predstavit ze sa moze stat ze to nebude vediet urobit.
> 
> Hmm, asi je to takto vporiadku :-D

Alebo tam bude len na FE/django admine moznost upravit ten textfield?

2020-10-25 23:49 UTC, kovacspe commented
JJ bude sa to dat v django admine ... a to mi prišlo celkom fajn že upravis ten json

2020-10-26 01:51 UTC, Matushl approved these changes

2020-10-26 10:08 UTC, merged